language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
     - PLATFORMIO_CI_SRC=PIO_TEMPLATE/src/
#     - PLATFORMIO_CI_SRC=src/

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="include/" --lib="PIO_TEMPLATE/.pio/libdeps/esp32dev/PCF8563_Library/" --lib="PIO_TEMPLATE/.pio/libdeps/esp32dev/NTP/" --lib="PIO_TEMPLATE/.pio/libdeps/esp32dev/EasyButton/" --lib="PIO_TEMPLATE/.pio/libdeps/esp32dev/TFT_eSPI/" --lib="PIO_TEMPLATE/.pio/libdeps/esp32dev/WifiManager/" --board=esp32dev

